### ISSUE TITLE
Article-List: valid price and crossed-out price, both 3-digit, don't fit into one line

### ISSUE THREAD

**Issue by ckleis** [chameleon-system/chameleon-shop-theme-bundle#29]
**Describe the bug**
In article lists with a valid price with 3 digits and a crossed out price with 3 digits, the two prices no longer fit into one line.

![Selection_400](https://user-images.githubusercontent.com/26296728/65420288-0adb7980-de01-11e9-8464-4c2bd99099ff.jpg)

**Affected version(s)**
6.3.x

**Comment by ckleis** [comment]
On small mobile devices (width lower than 450px) the valid price and the crossed-out price don't fit into one line. In this case the crossed-out price is placed (absolute) above the valid price into an empty line.
Thus a line break is prevented and the article boxes always keep the same height.

**Comment by ckleis** [comment]
A similar problem in Product-List is fixed with this issue:
In some mobile browsers, the "Sales" and "New" buttons are displayed in 2 lines. However, they should always be displayed next to each other. Some browsers set a padding-inline-start of 40px to the ul-element. This leads to the line break.
To overwrite this, the ul-element in the infoline needs a padding-left: 0;

**Comment by esono-anja** [comment]
fixed in 6.3, but not in 7.0
