### ISSUE TITLE
move shop menu button to fixed header

### ISSUE THREAD

**Issue by ckleis** [chameleon-system/chameleon-shop-theme-bundle#31]
**Describe the solution you'd like**
On mobile devices the button for the shop navigation should move to the fixed header beside the sevice button. The search field can then extend across the entire width of the screen.

**Possible solution (if any)**
![Selection_401](https://user-images.githubusercontent.com/26296728/65422637-5bee6c00-de07-11e9-9a6b-6d15017940e3.jpg)

**Comment by ckleis** [comment]
https://github.com/chameleon-system/chameleon-shop-theme-bundle/pull/32

**Comment by esono-anja** [comment]
The shop navigation is still next to the search field and below the service navigation in 7.0 (ok in 6.3)
